### ISSUE TITLE
Remove black Text-Background of titlebar-text?

### ISSUE THREAD

**Issue by NiZi9** [minusium/MicaForEveryone#13]
Is there a way to get rid of the black Background of the titlebar text?

**Comment by minusium** [comment]
It's a bug in DWM. I'm not sure if I can do anything about it.

**Comment by dongle-the-gadget** [comment]
I'll just flag this as won't fix, but still keep this open for now.

**Comment by NiZi9** [comment]
Thanks a lot, maybe there will be a way to fix it somehow in the future.
I've been wondering, is it at least possible to change that background colour so I could match it to my background/mica-effect-colour on my local machine? Or is it determined by the OS and can't be changed?

**Comment by minusium** [comment]
> is it determined by the OS and can't be changed?
Yes, it's that black background (that's white in light mode) is rendered by dwm for a bug in dwm itself.

**Comment by Void48** [comment]
February 16, 2022 - This is now fixed in the [Windows 11 Insider Preview Build 22557](https://blogs.windows.com/windows-insider/2022/02/16/announcing-windows-11-insider-preview-build-22557/) 🎉😄 
![image](https://user-images.githubusercontent.com/85196642/154405562-2a976171-6b5d-4dfa-97c8-d2acb74363a1.png)
![image](https://user-images.githubusercontent.com/85196642/154405578-9a0f6e54-5333-468b-94f8-799c1cdf1857.png)

**Comment by dongle-the-gadget** [comment]
I think I will close this as it's basically resolved in 22557.
